language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
script: inv test
after_success: coveralls
notifications:
  email: false
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
